package dev.maxdubmors.mapmethod.core.designsystem.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

// "Paper + graphite": the colour scheme used wherever dynamic color is unavailable (Android 10-11)
// or turned off. Generated with Material Color Utilities (SchemeNeutral, 2021 spec, contrast 0)
// from the graphite seed #3C4043, so every role follows the Material 3 tonal system.
// Regenerate rather than hand-tune single roles, or the tonal relationships between them break.

internal fun fallbackColorScheme(darkTheme: Boolean): ColorScheme =
    if (darkTheme) PaperGraphiteDarkColorScheme else PaperGraphiteLightColorScheme

private val PaperGraphiteLightColorScheme: ColorScheme =
    lightColorScheme(
        primary = Color(0xFF536069),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFD7E4EE),
        onPrimaryContainer = Color(0xFF3C4850),
        inversePrimary = Color(0xFFBBC8D2),
        secondary = Color(0xFF585F64),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFDCE3E9),
        onSecondaryContainer = Color(0xFF41484D),
        tertiary = Color(0xFF4E616D),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFD1E5F3),
        onTertiaryContainer = Color(0xFF364955),
        background = Color(0xFFFBF9F9),
        onBackground = Color(0xFF1B1C1C),
        surface = Color(0xFFFBF9F9),
        onSurface = Color(0xFF1B1C1C),
        surfaceVariant = Color(0xFFE4E2E3),
        onSurfaceVariant = Color(0xFF464747),
        surfaceTint = Color(0xFF536069),
        inverseSurface = Color(0xFF303031),
        inverseOnSurface = Color(0xFFF2F0F1),
        error = Color(0xFFBA1A1A),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFFFDAD6),
        onErrorContainer = Color(0xFF93000A),
        outline = Color(0xFF777778),
        outlineVariant = Color(0xFFC7C6C7),
        scrim = Color(0xFF000000),
        surfaceBright = Color(0xFFFBF9F9),
        surfaceContainer = Color(0xFFEFEDEE),
        surfaceContainerHigh = Color(0xFFE9E8E8),
        surfaceContainerHighest = Color(0xFFE4E2E3),
        surfaceContainerLow = Color(0xFFF5F3F4),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceDim = Color(0xFFDBD9DA),
        primaryFixed = Color(0xFFD7E4EE),
        primaryFixedDim = Color(0xFFBBC8D2),
        onPrimaryFixed = Color(0xFF111D24),
        onPrimaryFixedVariant = Color(0xFF3C4850),
        secondaryFixed = Color(0xFFDCE3E9),
        secondaryFixedDim = Color(0xFFC0C7CD),
        onSecondaryFixed = Color(0xFF151C21),
        onSecondaryFixedVariant = Color(0xFF41484D),
        tertiaryFixed = Color(0xFFD1E5F3),
        tertiaryFixedDim = Color(0xFFB5C9D7),
        onTertiaryFixed = Color(0xFF091E28),
        onTertiaryFixedVariant = Color(0xFF364955),
    )

private val PaperGraphiteDarkColorScheme: ColorScheme =
    darkColorScheme(
        primary = Color(0xFFBBC8D2),
        onPrimary = Color(0xFF26323A),
        primaryContainer = Color(0xFF3C4850),
        onPrimaryContainer = Color(0xFFD7E4EE),
        inversePrimary = Color(0xFF536069),
        secondary = Color(0xFFC0C7CD),
        onSecondary = Color(0xFF2A3136),
        secondaryContainer = Color(0xFF41484D),
        onSecondaryContainer = Color(0xFFDCE3E9),
        tertiary = Color(0xFFB5C9D7),
        onTertiary = Color(0xFF20333D),
        tertiaryContainer = Color(0xFF364955),
        onTertiaryContainer = Color(0xFFD1E5F3),
        background = Color(0xFF131314),
        onBackground = Color(0xFFE4E2E3),
        surface = Color(0xFF131314),
        onSurface = Color(0xFFE4E2E3),
        surfaceVariant = Color(0xFF464747),
        onSurfaceVariant = Color(0xFFC7C6C7),
        surfaceTint = Color(0xFFBBC8D2),
        inverseSurface = Color(0xFFE4E2E3),
        inverseOnSurface = Color(0xFF303031),
        error = Color(0xFFFFB4AB),
        onError = Color(0xFF690005),
        errorContainer = Color(0xFF93000A),
        onErrorContainer = Color(0xFFFFDAD6),
        outline = Color(0xFF919091),
        outlineVariant = Color(0xFF464747),
        scrim = Color(0xFF000000),
        surfaceBright = Color(0xFF39393A),
        surfaceContainer = Color(0xFF1F2020),
        surfaceContainerHigh = Color(0xFF292A2B),
        surfaceContainerHighest = Color(0xFF343536),
        surfaceContainerLow = Color(0xFF1B1C1C),
        surfaceContainerLowest = Color(0xFF0D0E0F),
        surfaceDim = Color(0xFF131314),
        primaryFixed = Color(0xFFD7E4EE),
        primaryFixedDim = Color(0xFFBBC8D2),
        onPrimaryFixed = Color(0xFF111D24),
        onPrimaryFixedVariant = Color(0xFF3C4850),
        secondaryFixed = Color(0xFFDCE3E9),
        secondaryFixedDim = Color(0xFFC0C7CD),
        onSecondaryFixed = Color(0xFF151C21),
        onSecondaryFixedVariant = Color(0xFF41484D),
        tertiaryFixed = Color(0xFFD1E5F3),
        tertiaryFixedDim = Color(0xFFB5C9D7),
        onTertiaryFixed = Color(0xFF091E28),
        onTertiaryFixedVariant = Color(0xFF364955),
    )
